---
- name: Install Apache on Amazon Linux
  hosts: groupe1 
  become: true

  tasks:
    - name: Update package cache
      yum:
        name: "*"
        state: latest
      become: true

    - name: Install Apache
      yum:
        name: httpd
        state: present
      become: true

    - name: Start Apache service
      service:
        name: httpd
        state: started
      become: true

    - name: Enable Apache service
      service:
        name: httpd
        enabled: true
      become: true
